// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `com.vanvixi.file_saver_ffi.FileSaver`
class FileSaver extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<FileSaver> $type;

  @jni$_.internal
  FileSaver.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/vanvixi/file_saver_ffi/FileSaver',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<FileSaver?> nullableType =
      $FileSaver$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<FileSaver> type = $FileSaver$Type$();
  static final _id_new$ = _class.constructorId(r'(Landroid/content/Context;)V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(android.content.Context context)`
  /// The returned object must be released after use, by calling the [release] method.
  factory FileSaver(jni$_.JObject context) {
    final _$context = context.reference;
    return FileSaver.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$context.pointer,
      ).reference,
    );
  }

  static final _id_saveBytes = _class.instanceMethodId(
    r'saveBytes',
    r'([BLjava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;ILcom/vanvixi/file_saver_ffi/models/ProgressCallback;)V',
  );

  static final _saveBytes =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              int,
              jni$_.Pointer<jni$_.Void>,
              int,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun saveBytes(fileData: kotlin.ByteArray, baseFileName: kotlin.String, extension: kotlin.String, mimeType: kotlin.String, saveLocationIndex: kotlin.Int, subDir: kotlin.String?, conflictMode: kotlin.Int, callback: com.vanvixi.file_saver_ffi.models.ProgressCallback): kotlin.Unit`
  void saveBytes(
    jni$_.JByteArray bs,
    jni$_.JString string,
    jni$_.JString string1,
    jni$_.JString string2,
    int i,
    jni$_.JString? string3,
    int i1,
    ProgressCallback progressCallback,
  ) {
    final _$bs = bs.reference;
    final _$string = string.reference;
    final _$string1 = string1.reference;
    final _$string2 = string2.reference;
    final _$string3 = string3?.reference ?? jni$_.jNullReference;
    final _$progressCallback = progressCallback.reference;
    _saveBytes(
      reference.pointer,
      _id_saveBytes as jni$_.JMethodIDPtr,
      _$bs.pointer,
      _$string.pointer,
      _$string1.pointer,
      _$string2.pointer,
      i,
      _$string3.pointer,
      i1,
      _$progressCallback.pointer,
    ).check();
  }
}

final class $FileSaver$NullableType$ extends jni$_.JType<FileSaver?> {
  @jni$_.internal
  const $FileSaver$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/vanvixi/file_saver_ffi/FileSaver;';

  @jni$_.internal
  @core$_.override
  FileSaver? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : FileSaver.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<FileSaver?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($FileSaver$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($FileSaver$NullableType$) &&
        other is $FileSaver$NullableType$;
  }
}

final class $FileSaver$Type$ extends jni$_.JType<FileSaver> {
  @jni$_.internal
  const $FileSaver$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/vanvixi/file_saver_ffi/FileSaver;';

  @jni$_.internal
  @core$_.override
  FileSaver fromReference(jni$_.JReference reference) =>
      FileSaver.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<FileSaver?> get nullableType => const $FileSaver$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($FileSaver$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($FileSaver$Type$) && other is $FileSaver$Type$;
  }
}

/// from: `com.vanvixi.file_saver_ffi.models.ProgressCallback`
class ProgressCallback extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<ProgressCallback> $type;

  @jni$_.internal
  ProgressCallback.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/vanvixi/file_saver_ffi/models/ProgressCallback',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<ProgressCallback?> nullableType =
      $ProgressCallback$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<ProgressCallback> type = $ProgressCallback$Type$();
  static final _id_onEvent = _class.instanceMethodId(
    r'onEvent',
    r'(IDLjava/lang/String;Ljava/lang/String;)V',
  );

  static final _onEvent =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Int32,
                    jni$_.Double,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              int,
              double,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onEvent(eventType: kotlin.Int, progress: kotlin.Double, data: kotlin.String?, message: kotlin.String?): kotlin.Unit`
  void onEvent(int i, double d, jni$_.JString? string, jni$_.JString? string1) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    _onEvent(
      reference.pointer,
      _id_onEvent as jni$_.JMethodIDPtr,
      i,
      d,
      _$string.pointer,
      _$string1.pointer,
    ).check();
  }

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<int, $ProgressCallback> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(0, descriptor.address, args.address),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'onEvent(IDLjava/lang/String;Ljava/lang/String;)V') {
        _$impls[$p]!.onEvent(
          $a![0]!
              .as(const jni$_.$JInteger$Type$(), releaseOriginal: true)
              .intValue(releaseOriginal: true),
          $a![1]!
              .as(const jni$_.$JDouble$Type$(), releaseOriginal: true)
              .doubleValue(releaseOriginal: true),
          $a![2]?.as(const jni$_.$JString$Type$(), releaseOriginal: true),
          $a![3]?.as(const jni$_.$JString$Type$(), releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $ProgressCallback $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'com.vanvixi.file_saver_ffi.models.ProgressCallback',
      $p,
      _$invokePointer,
      [
        if ($impl.onEvent$async)
          r'onEvent(IDLjava/lang/String;Ljava/lang/String;)V',
      ],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory ProgressCallback.implement($ProgressCallback $impl) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return ProgressCallback.fromReference($i.implementReference());
  }
}

abstract base mixin class $ProgressCallback {
  factory $ProgressCallback({
    required void Function(
      int i,
      double d,
      jni$_.JString? string,
      jni$_.JString? string1,
    )
    onEvent,
    bool onEvent$async,
  }) = _$ProgressCallback;

  void onEvent(int i, double d, jni$_.JString? string, jni$_.JString? string1);
  bool get onEvent$async => false;
}

final class _$ProgressCallback with $ProgressCallback {
  _$ProgressCallback({
    required void Function(
      int i,
      double d,
      jni$_.JString? string,
      jni$_.JString? string1,
    )
    onEvent,
    this.onEvent$async = false,
  }) : _onEvent = onEvent;

  final void Function(
    int i,
    double d,
    jni$_.JString? string,
    jni$_.JString? string1,
  )
  _onEvent;
  final bool onEvent$async;

  void onEvent(int i, double d, jni$_.JString? string, jni$_.JString? string1) {
    return _onEvent(i, d, string, string1);
  }
}

final class $ProgressCallback$NullableType$
    extends jni$_.JType<ProgressCallback?> {
  @jni$_.internal
  const $ProgressCallback$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/vanvixi/file_saver_ffi/models/ProgressCallback;';

  @jni$_.internal
  @core$_.override
  ProgressCallback? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : ProgressCallback.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<ProgressCallback?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ProgressCallback$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ProgressCallback$NullableType$) &&
        other is $ProgressCallback$NullableType$;
  }
}

final class $ProgressCallback$Type$ extends jni$_.JType<ProgressCallback> {
  @jni$_.internal
  const $ProgressCallback$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/vanvixi/file_saver_ffi/models/ProgressCallback;';

  @jni$_.internal
  @core$_.override
  ProgressCallback fromReference(jni$_.JReference reference) =>
      ProgressCallback.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<ProgressCallback?> get nullableType =>
      const $ProgressCallback$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ProgressCallback$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ProgressCallback$Type$) &&
        other is $ProgressCallback$Type$;
  }
}
