// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

class FileSaverFFI {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FileSaverFFI(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FileSaverFFI.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Initialize Dart API for NativePort communication.
  /// Must be called before using file_saver_save_bytes.
  ///
  /// @param data Pointer from NativeApi.initializeApiDLData
  /// @return 0 on success, -1 on failure
  int initDartApiDl(ffi.Pointer<ffi.Void> data) {
    return _initDartApiDl(data);
  }

  late final _initDartApiDlPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>(
        'file_saver_init_dart_api_dl',
      );
  late final _initDartApiDl =
      _initDartApiDlPtr.asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.Void> init() {
    return _init();
  }

  late final _initPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function()>>(
        'file_saver_init',
      );
  late final _init = _initPtr.asFunction<ffi.Pointer<ffi.Void> Function()>();

  void dispose(ffi.Pointer<ffi.Void> instance) {
    return _dispose(instance);
  }

  late final _disposePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'file_saver_dispose',
      );
  late final _dispose =
      _disposePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  /// Cancel an ongoing save operation.
  ///
  /// @param tokenId Token ID returned from file_saver_save_bytes or file_saver_save_file
  void cancel(int tokenId) {
    return _cancel(tokenId);
  }

  late final _cancelPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Uint64)>>(
        'file_saver_cancel',
      );
  late final _cancel = _cancelPtr.asFunction<void Function(int)>();

  /// Save file bytes asynchronously with progress reporting via NativePort.
  ///
  /// Progress messages sent to native_port:
  /// - Started:    [0]
  /// - Progress:   [1, progress]    (progress is 0.0 to 1.0)
  /// - Error:      [2, errorCode, errorMessage]
  /// - Success:    [3, fileUri]
  /// - Cancelled:  [4]
  ///
  /// @param instance FileSaver instance from file_saver_init
  /// @param fileData Byte array of file content
  /// @param fileDataLength Length of fileData
  /// @param baseFileName File name without extension
  /// @param extension File extension without dot
  /// @param mimeType MIME type string
  /// @param saveLocation Save location index (0-4)
  /// @param subDir Optional subdirectory (can be NULL)
  /// @param conflictMode Conflict resolution mode (0-3)
  /// @param native_port Dart NativePort for progress reporting
  /// @return Token ID for cancellation
  int saveBytes(
    ffi.Pointer<ffi.Void> instance,
    ffi.Pointer<ffi.Uint8> fileData,
    int fileDataLength,
    ffi.Pointer<ffi.Char> baseFileName,
    ffi.Pointer<ffi.Char> extension,
    ffi.Pointer<ffi.Char> mimeType,
    int saveLocation,
    ffi.Pointer<ffi.Char> subDir,
    int conflictMode,
    int native_port,
  ) {
    return _saveBytes(
      instance,
      fileData,
      fileDataLength,
      baseFileName,
      extension,
      mimeType,
      saveLocation,
      subDir,
      conflictMode,
      native_port,
    );
  }

  late final _saveBytesPtr = _lookup<
    ffi.NativeFunction<
      ffi.Uint64 Function(
        ffi.Pointer<ffi.Void>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Int64,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Int32,
        ffi.Pointer<ffi.Char>,
        ffi.Int32,
        ffi.Int64,
      )
    >
  >('file_saver_save_bytes');
  late final _saveBytes =
      _saveBytesPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Uint8>,
              int,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              int,
              ffi.Pointer<ffi.Char>,
              int,
              int,
            )
          >();

  /// Save file from source path asynchronously with progress reporting via
  /// NativePort.
  ///
  /// Reads source file in chunks without loading into memory - suitable for large
  /// files. Handles security-scoped resources (Files app) and iCloud file
  /// downloads.
  ///
  /// Progress messages sent to native_port:
  /// - Started:    [0]
  /// - Progress:   [1, progress]    (progress is 0.0 to 1.0)
  /// - Error:      [2, errorCode, errorMessage]
  /// - Success:    [3, fileUri]
  /// - Cancelled:  [4]
  ///
  /// @param instance FileSaver instance from file_saver_init
  /// @param filePath Source file path (file:// URI)
  /// @param baseFileName Target file name without extension
  /// @param extension File extension without dot
  /// @param mimeType MIME type string
  /// @param saveLocation Save location index (0-1 for iOS)
  /// @param subDir Optional subdirectory (can be NULL)
  /// @param conflictMode Conflict resolution mode (0-3)
  /// @param native_port Dart NativePort for progress reporting
  /// @return Token ID for cancellation
  int saveFile(
    ffi.Pointer<ffi.Void> instance,
    ffi.Pointer<ffi.Char> filePath,
    ffi.Pointer<ffi.Char> baseFileName,
    ffi.Pointer<ffi.Char> extension,
    ffi.Pointer<ffi.Char> mimeType,
    int saveLocation,
    ffi.Pointer<ffi.Char> subDir,
    int conflictMode,
    int native_port,
  ) {
    return _saveFile(
      instance,
      filePath,
      baseFileName,
      extension,
      mimeType,
      saveLocation,
      subDir,
      conflictMode,
      native_port,
    );
  }

  late final _saveFilePtr = _lookup<
    ffi.NativeFunction<
      ffi.Uint64 Function(
        ffi.Pointer<ffi.Void>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Int32,
        ffi.Pointer<ffi.Char>,
        ffi.Int32,
        ffi.Int64,
      )
    >
  >('file_saver_save_file');
  late final _saveFile =
      _saveFilePtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              int,
              ffi.Pointer<ffi.Char>,
              int,
              int,
            )
          >();

  /// Save file from network URL asynchronously with progress reporting via
  /// NativePort.
  ///
  /// Downloads file at native level to avoid double storage:
  /// - Documents: Downloads directly to target path
  /// - Photos: Downloads to tmp, saves to Photos Library, deletes tmp
  ///
  /// Progress messages sent to native_port:
  /// - Started:    [0]
  /// - Progress:   [1, progress]    (progress is 0.0 to 1.0)
  /// - Error:      [2, errorCode, errorMessage]
  /// - Success:    [3, fileUri]
  /// - Cancelled:  [4]
  ///
  /// @param instance FileSaver instance from file_saver_init
  /// @param urlString URL to download from
  /// @param headersJson Optional JSON string of HTTP headers (can be NULL)
  /// @param timeoutSeconds Timeout in seconds for network request
  /// @param baseFileName File name without extension
  /// @param extension File extension without dot
  /// @param mimeType MIME type string
  /// @param saveLocation Save location index (0-1 for iOS)
  /// @param subDir Optional subdirectory (can be NULL)
  /// @param conflictMode Conflict resolution mode (0-3)
  /// @param native_port Dart NativePort for progress reporting
  /// @return Token ID for cancellation
  int saveNetwork(
    ffi.Pointer<ffi.Void> instance,
    ffi.Pointer<ffi.Char> urlString,
    ffi.Pointer<ffi.Char> headersJson,
    int timeoutSeconds,
    ffi.Pointer<ffi.Char> baseFileName,
    ffi.Pointer<ffi.Char> extension,
    ffi.Pointer<ffi.Char> mimeType,
    int saveLocation,
    ffi.Pointer<ffi.Char> subDir,
    int conflictMode,
    int native_port,
  ) {
    return _saveNetwork(
      instance,
      urlString,
      headersJson,
      timeoutSeconds,
      baseFileName,
      extension,
      mimeType,
      saveLocation,
      subDir,
      conflictMode,
      native_port,
    );
  }

  late final _saveNetworkPtr = _lookup<
    ffi.NativeFunction<
      ffi.Uint64 Function(
        ffi.Pointer<ffi.Void>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Int32,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Int32,
        ffi.Pointer<ffi.Char>,
        ffi.Int32,
        ffi.Int64,
      )
    >
  >('file_saver_save_network');
  late final _saveNetwork =
      _saveNetworkPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              int,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              int,
              ffi.Pointer<ffi.Char>,
              int,
              int,
            )
          >();

  /// Save bytes to user-selected directory (saveAs).
  ///
  /// Saves file bytes to a directory previously selected via DirPicker.pick() (package:dir_picker).
  /// Uses security-scoped resource access for the selected directory.
  ///
  /// Progress messages sent to native_port:
  /// - Started:    [0]
  /// - Progress:   [1, progress]    (progress is 0.0 to 1.0)
  /// - Error:      [2, errorCode, errorMessage]
  /// - Success:    [3, fileUri]
  /// - Cancelled:  [4]
  ///
  /// @param instance FileSaver instance from file_saver_init
  /// @param fileData Byte array of file content
  /// @param fileDataLength Length of fileData
  /// @param directoryUri Directory URI from DirPicker.pick() (package:dir_picker)
  /// @param baseFileName File name without extension
  /// @param extension File extension without dot
  /// @param conflictMode Conflict resolution mode (0-3)
  /// @param native_port Dart NativePort for progress reporting
  /// @return Token ID for cancellation
  int saveBytesAs(
    ffi.Pointer<ffi.Void> instance,
    ffi.Pointer<ffi.Uint8> fileData,
    int fileDataLength,
    ffi.Pointer<ffi.Char> directoryUri,
    ffi.Pointer<ffi.Char> baseFileName,
    ffi.Pointer<ffi.Char> extension,
    int conflictMode,
    int native_port,
  ) {
    return _saveBytesAs(
      instance,
      fileData,
      fileDataLength,
      directoryUri,
      baseFileName,
      extension,
      conflictMode,
      native_port,
    );
  }

  late final _saveBytesAsPtr = _lookup<
    ffi.NativeFunction<
      ffi.Uint64 Function(
        ffi.Pointer<ffi.Void>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Int64,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Int32,
        ffi.Int64,
      )
    >
  >('file_saver_save_bytes_as');
  late final _saveBytesAs =
      _saveBytesAsPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Uint8>,
              int,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              int,
              int,
            )
          >();

  /// Save file to user-selected directory (saveAs).
  ///
  /// Copies a file to a directory previously selected via DirPicker.pick() (package:dir_picker).
  /// Uses security-scoped resource access for the selected directory.
  ///
  /// Progress messages sent to native_port:
  /// - Started:    [0]
  /// - Progress:   [1, progress]    (progress is 0.0 to 1.0)
  /// - Error:      [2, errorCode, errorMessage]
  /// - Success:    [3, fileUri]
  /// - Cancelled:  [4]
  ///
  /// @param instance FileSaver instance from file_saver_init
  /// @param filePath Source file path (file:// URI)
  /// @param directoryUri Directory URI from DirPicker.pick() (package:dir_picker)
  /// @param baseFileName File name without extension
  /// @param extension File extension without dot
  /// @param conflictMode Conflict resolution mode (0-3)
  /// @param native_port Dart NativePort for progress reporting
  /// @return Token ID for cancellation
  int saveFileAs(
    ffi.Pointer<ffi.Void> instance,
    ffi.Pointer<ffi.Char> filePath,
    ffi.Pointer<ffi.Char> directoryUri,
    ffi.Pointer<ffi.Char> baseFileName,
    ffi.Pointer<ffi.Char> extension,
    int conflictMode,
    int native_port,
  ) {
    return _saveFileAs(
      instance,
      filePath,
      directoryUri,
      baseFileName,
      extension,
      conflictMode,
      native_port,
    );
  }

  late final _saveFileAsPtr = _lookup<
    ffi.NativeFunction<
      ffi.Uint64 Function(
        ffi.Pointer<ffi.Void>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Int32,
        ffi.Int64,
      )
    >
  >('file_saver_save_file_as');
  late final _saveFileAs =
      _saveFileAsPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              int,
              int,
            )
          >();

  /// Save network file to user-selected directory (saveAs).
  ///
  /// Downloads and saves a file to a directory previously selected via
  /// DirPicker.pick() (package:dir_picker). Uses security-scoped resource access.
  ///
  /// Progress messages sent to native_port:
  /// - Started:    [0]
  /// - Progress:   [1, progress]    (progress is 0.0 to 1.0)
  /// - Error:      [2, errorCode, errorMessage]
  /// - Success:    [3, fileUri]
  /// - Cancelled:  [4]
  ///
  /// @param instance FileSaver instance from file_saver_init
  /// @param urlString URL to download from
  /// @param headersJson Optional JSON string of HTTP headers (can be NULL)
  /// @param timeoutSeconds Timeout in seconds for network request
  /// @param directoryUri Directory URI from DirPicker.pick() (package:dir_picker)
  /// @param baseFileName File name without extension
  /// @param extension File extension without dot
  /// @param conflictMode Conflict resolution mode (0-3)
  /// @param native_port Dart NativePort for progress reporting
  /// @return Token ID for cancellation
  int saveNetworkAs(
    ffi.Pointer<ffi.Void> instance,
    ffi.Pointer<ffi.Char> urlString,
    ffi.Pointer<ffi.Char> headersJson,
    int timeoutSeconds,
    ffi.Pointer<ffi.Char> directoryUri,
    ffi.Pointer<ffi.Char> baseFileName,
    ffi.Pointer<ffi.Char> extension,
    int conflictMode,
    int native_port,
  ) {
    return _saveNetworkAs(
      instance,
      urlString,
      headersJson,
      timeoutSeconds,
      directoryUri,
      baseFileName,
      extension,
      conflictMode,
      native_port,
    );
  }

  late final _saveNetworkAsPtr = _lookup<
    ffi.NativeFunction<
      ffi.Uint64 Function(
        ffi.Pointer<ffi.Void>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Int32,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Int32,
        ffi.Int64,
      )
    >
  >('file_saver_save_network_as');
  late final _saveNetworkAs =
      _saveNetworkAsPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              int,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              int,
              int,
            )
          >();
}
